AWSTemplateFormatVersion: "2010-09-09"
Description: Example EC2 template
Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-064efdb82ae15e93f" # Latest Ubuntu 18.04 in ca-central-1; https://cloud-images.ubuntu.com/locator/ec2/
      InstanceType: t2.micro
      KeyName: some-keyname-in-aws
