FROM debian:buster

ARG PKG=alertmanager
ARG VER=0.20.0

RUN apt-get update && apt-get install -y curl

RUN curl -L -o ${PKG}.tar.gz "https://github.com/prometheus/${PKG}/releases/download/v${VER}/${PKG}-${VER}.linux-amd64.tar.gz"

RUN tar -xzf ${PKG}.tar.gz && rm ${PKG}.tar.gz

WORKDIR ${PKG}-${VER}.linux-amd64

# Add & validate config file(s) so build can fail gracefully
COPY alertmanager.yaml alertmanager.yaml
RUN rm *.yml \
    && ./amtool check-config *.yaml

EXPOSE 9093

CMD ["./alertmanager", "--config.file=alertmanager.yaml"]
