FROM debian:buster

ARG PKG=prometheus
ARG VER=2.14.0

RUN apt-get update && apt-get install -y curl

RUN curl -L -o ${PKG}.tar.gz "https://github.com/prometheus/${PKG}/releases/download/v${VER}/${PKG}-${VER}.linux-amd64.tar.gz"

RUN tar -xzf ${PKG}.tar.gz && rm ${PKG}.tar.gz

WORKDIR ${PKG}-${VER}.linux-amd64

# Add & validate config file(s) so build can fail gracefully
COPY prometheus.yaml prometheus.yaml
RUN rm *.yml \
    && ./promtool check config *.yaml

EXPOSE 9090

CMD ["./prometheus", "--config.file=prometheus.yaml"]
