# You likely don't want to run all of these services on the same host (beause
# that's pointless), but this is how their configs would look individually.
# Includes blocks for applications that are instrumented for Prometheus to hit
# in the wild.

version: "3"

services:

  prometheus:
    container_name: prometheus
    build:
      context: .
      dockerfile: ./Dockerfile-prometheus
    image: prometheus:latest
    ports:
      - "9090:9090"
    restart: always

  node_exporter:
    container_name: node_exporter
    build:
      context: .
      dockerfile: ./Dockerfile-node_exporter
    image: node_exporter:latest
    ports:
      - "9100:9100"
    restart: always

  alertmanager:
    container_name: alertmanager
    build:
      context: .
      dockerfile: ./Dockerfile-alertmanager
    image: alertmanager:latest
    ports:
      - "9093:9093"
    restart: always
