# App Engine config, configured to be lowest-cost
runtime: python37

# Instance class; note that F1 was almost too small for this to even run
instance_class: F2

# Set some defaults (or lower) as placeholders
automatic_scaling: 
  target_cpu_utilization: 0.6
  min_instances: 0 # no instances if no load
  max_instances: 2
  min_idle_instances: 0
  max_idle_instances: 1
  max_concurrent_requests: 8
