- hosts: all # you can refer to group names from inventory file, as well
  tasks:
    - name: Install core system/development tools
      become: yes
      apt:
        update_cache: yes
        name:
          - bash
          - jq
          - less
          - man
          - nano
          - git
          - python3
          - python3-pip
          - python3-venv
          - shellcheck
        state: latest
