---
- hosts: localhost
  tasks:
    - name: Install system tools
      apt:
        name:
          - bash
          - jq
          - less
          - man
          - nano
          - shellcheck
        state: latest
